import glob
import numpy as np 
import nibabel as nib
import argparse

def back_converter(args):
	
	clinica_CAPS_path = args.clinica_CAPS_path

	# We will gather all brain numpys generated by the running the file fs_brain_mgz_to_npy.py 
	# Convert them to Nifti Image format using nibabel, store them in place next to where the brain.mgz's and numpys are present

	all_brain_npys = glob.glob(clinica_CAPS_path+"/*/*/*/*/*/*/*/*.npy")

	print("Total number of brain files ", len(all_brain_npys))

	for file in all_brain_npys:

		data = np.load(file)
		img = nib.Nifti1Image(data, np.eye(4)) 
		img.to_filename((file[:-4]+'.nii.gz'))

		print('Saving ', file[:-4]+'.nii.gz')

if __name__ == '__main__':
	arg_parser = argparse.ArgumentParser(description='Convert numpy to nifit')
	arg_parser.add_argument('--clinica_CAPS_path', type=str, default="../clinica_CAPS/", help="Path to clinica fressurfer output CAPS folder")
	arg_parser.add_argument('--rotate', default=False, action='store_true')
	args = arg_parser.parse_args()
	back_converter(args)	